In [3]:
import gymnasium

In [5]:
env = gymnasium.make("CartPole-v1")

In [7]:
env.reset()
env.render()

/home/led/miniconda3/lib/python3.11/site-packages/gymnasium/envs/classic_control/cartpole.py:215: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(


In [11]:
import torch

In [12]:
a = torch.zeros(0)

In [13]:
a

tensor([])

In [14]:
b = torch.tensor([1, 2, 3, 4])

In [15]:
torch.cat((a, b))

tensor([1., 2., 3., 4.])

In [19]:
b.numpy()[::-1]

array([4, 3, 2, 1])

In [22]:
b.flip(0)

tensor([4, 3, 2, 1])

In [26]:
import numpy as np

In [27]:
np.concatenate((np.zeros(0), np.array([1, 2, 3, 4])))

array([1., 2., 3., 4.])

In [31]:
[1, 2,3].extend([1]*0)

In [28]:
np.append(np.zeros(0), 1)

array([1.])

In [17]:
import scipy

In [24]:
out = scipy.signal.lfilter([1], [1, float(-1)], b.flip(0), axis=0)[::-1]

In [25]:
out

numpy.ndarray

In [16]:
import scipy

In [10]:
env.action_space

Discrete(2)